Add rules_testing to bazelci.py
bazelbuild/continuous-integration pull request #1564
Opened 2023-03-01 05:45 UTC by rickeylev

Work towards ##1549

2023-03-01 05:46 UTC, rickeylev commented
I think this part of the config is missing? I'm not familiar with these configs; just going off how I see rules_python and other rules configured.

2023-03-01 17:21 UTC, rickeylev commented
Thanks, I couldn't find the url for its builds. I've got it setup to trigger on PRs now. I've filed https://github.com/bazelbuild/rules_testing/issues/11 to fix the breakages. I'll re-request review when our CI is green.

2023-03-04 18:09 UTC, rickeylev commented
Ok, rules_testing passing at head. PTAL

2023-03-06 08:52 UTC, meteorcloudy requested changes
LGTM, just needs to fix the rule name in the URL.

2023-03-06 08:52 UTC, meteorcloudy commented on buildkite/bazelci.py
> +        "http_config": "https://raw.githubusercontent.com/bazelbuild/rules_python/master/.bazelci/presubmit.yml",
```suggestion
        "http_config": "https://raw.githubusercontent.com/bazelbuild/rules_testing/master/.bazelci/presubmit.yml",
```

2023-03-06 16:30 UTC, rickeylev commented
Fixed, PTAL

2023-03-06 16:39 UTC, meteorcloudy approved these changes

2023-03-06 16:39 UTC, merged

2023-03-06 16:41 UTC, meteorcloudy commented
Started a build to update the last green commit for rules_testing: https://buildkite.com/bazel/rules-testing/builds/38

Tonight's nightly downstream run should be able to pick up rules_testing correctly.